##################################################################################################
# Author: Kawser
# Version: 1.0.0
# Description: YAML configuration for creating kube-drive-storage StorageClass
#
#
#
# To apply:
#
#   kubectl apply -f kube-drive-storage.yaml
#
#
##################################################################################################


kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kube-drive-storage


provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
