apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-drive-pv


spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kube-drive-storage
  local:
    path: /mnt/disk/KubeDrive
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - usbbks2
