##################################################################################################
# Author: Kawser
# Version: 1.0.0
# Description: YAML configuration for creating docker-registry-secrets ConfigMap
#
#
#
# To apply:
#
#   kubectl apply -f docker-registry-secrets.yaml
#
#
##################################################################################################


apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-secrets
  namespace: default


data:
  # update with appropriate contents
  chain.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  private.key: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
  htpasswd: |+
    user:hased.pass
