##################################################################################################
# Author: Kawser
# Version: 1.0.0
# Description: YAML configuration for creating docker-registry Service
#
#
#
# To apply:
#
#   kubectl apply -f service.yaml
#
#
##################################################################################################


apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
    service: docker-registry


spec:
  externalIPs:
    - 192.168.0.100

  ports:
    - port: 443
      targetPort: 443

  selector:
    app: docker-registry

  # type: NodePort
