##################################################################################################
# Author: Kawser
# Version: 1.0.0
# Description: YAML configuration for creating exgohttpheaders deployment
#
#
#
# To apply:
#
#   kubectl apply -f deployment.yaml
#
#
##################################################################################################


apiVersion: apps/v1
kind: Deployment
metadata:
  name: exgohttpheaders-slim
  labels:
    app: exgohttpheaders
    version: slim


spec:
  replicas: 1
  selector:
    matchLabels:
      app: exgohttpheaders
      version: slim

  template:
    metadata:
      labels:
        app: exgohttpheaders
        version: slim

    spec:
      containers:
      - name: exgohttpheaders
        image: mkawserm/exgohttpheaders:slim
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
